# Generated by Django 2.2 on 2019-06-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='apps_used',
            field=models.CharField(blank=True, choices=[('Bumble', 'Bumble'), ('CoffeeMeetsBagel', 'CoffeeMeetsBagel'), ('Grindr', 'Grindr'), ('Match', 'Match'), ('OkCupid', 'OkCupid'), ('POF', 'POF'), ('Hinge', 'Hinge'), ('Tinder', 'Tinder')], max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-Binary')], max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationship_goal',
            field=models.CharField(blank=True, choices=[('Relationship', 'Relationship'), ('Something Casual', 'Something Casual'), ('Not Sure', 'Not Sure'), ('Marriage', 'Marriage')], max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='zodiac',
            field=models.CharField(blank=True, choices=[('Aries', 'Aries'), ('Taurus', 'Taurus'), ('Gemini', 'Gemini'), ('Cancer', 'Cancer'), ('Leo', 'Leo'), ('Virgo', 'Virgo'), ('Libra', 'Libra'), ('Scorpio', 'Scorpio'), ('Sagittarius', 'Sagittarius'), ('Capricorn', 'Capricorn'), ('Aquarius', 'Aquarius'), ('Pisces', 'Pisces')], max_length=100),
        ),
    ]
