# Generated by Django 2.2 on 2019-06-18 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190618_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdv',
            name='rdv_time',
        ),
        migrations.AddField(
            model_name='rdv',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
