# Generated by Django 2.2 on 2019-06-18 17:51

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190618_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='phone',
        ),
        migrations.AddField(
            model_name='match',
            name='attraction',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
