# Generated by Django 2.2 on 2019-06-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190620_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='location',
            field=models.TextField(blank=True, verbose_name="Match's Location"),
        ),
        migrations.AlterField(
            model_name='match',
            name='meet',
            field=models.TextField(verbose_name='Where We Met'),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='rdv_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time of Date'),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='what',
            field=models.TextField(blank=True, verbose_name='Activity'),
        ),
    ]
