# Generated by Django 2.2 on 2019-06-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190615_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='user',
        ),
        migrations.AlterField(
            model_name='match',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
