# Generated by Django 2.2 on 2019-06-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190618_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
