# Generated by Django 2.2 on 2019-06-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190618_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
