# Generated by Django 2.2 on 2019-06-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_match_attraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
