# Generated by Django 2.2 on 2019-06-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190618_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='rdv_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
