# Generated by Django 2.2 on 2019-06-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rdv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='ghost',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='see_again',
            field=models.BooleanField(null=True),
        ),
    ]
