# Generated by Django 2.2 on 2019-06-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20190616_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='cancel',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
